# This is a basic workflow that is manually triggered
- name: Gatsby Publish
  uses: enriikke/gatsby-gh-pages-action@v2.1.1
  with:
    # A personal access token needed to push your site after it has been built.
    access-token: 
    # The branch expected by GitHub to have the static files needed for your site.
    deploy-branch: # optional, default is master
    # Additional arguments that get passed to `gatsby build`.
    gatsby-args: # optional, default is 
